---
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - run: npm ci
      - run:
          command: npm run start:ci
          background: true
      - run: npm run cypress
